#!/usr/bin/env bash
set -ue

sudo /usr/local/cuda-10.0/bin/nvprof --unified-memory-profiling per-process-device -m all --csv --log-file metrics_small_zemaitis_uvm.csv ../darknet --test_type activation --bidirection 0 -s 1
